repos:
-   repo: local
    hooks:
      - id: evaluate-changes
        name: Evaluate Changes
        entry: python scripts/evaluate_commit.py
        language: system
#        files: '\.py$'
        pass_filenames: true
